CREATE TABLE `Book` (
  `id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

create sequence hibernate_sequence;
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID INTEGER NOT NULL, SEQUENCE_VALUE INTEGER, PRIMARY KEY (ID));

CREATE TABLE CUSTOMER (
      CUST_ID INTEGER NOT NULL ,
      FIRST_NAME VARCHAR(50) ,
      LAST_NAME  VARCHAR(50) NOT NULL,
      STREET  VARCHAR(50),
      APPT  VARCHAR(20),
      CITY  VARCHAR(25),
      ZIP_CODE  VARCHAR(10) NOT NULL,
      EMAIL  VARCHAR(30) NOT NULL,
      LAST_UPDATED_TIME TIMESTAMP
);

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK Primary Key (CUST_ID);

CREATE TABLE PRODUCT (
      PROD_ID INTEGER NOT NULL ,
      PROD_NAME VARCHAR(50) NOT NULL,
      PROD_DESC  VARCHAR(200),
      REGULAR_PRICE  DOUBLE PRECISION,
      LAST_UPDATED_TIME TIMESTAMP
     
);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PK Primary Key (PROD_ID);
CREATE TABLE ORDERS (
      ORDER_ID INTEGER NOT NULL ,
      CUST_ID INTEGER NOT NULL ,
      TOTAL_PRICE  DOUBLE PRECISION,
      OREDER_DESC  VARCHAR(100),
      ORDER_DATE  TIMESTAMP,
      LAST_UPDATED_TIME TIMESTAMP
);
ALTER TABLE ORDERS ADD CONSTRAINT ORDER_PK Primary Key (ORDER_ID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDER_FK Foreign Key (CUST_ID) REFERENCES CUSTOMER (CUST_ID);
CREATE TABLE ORDER_DETAIL (
      ORDER_ID INTEGER NOT NULL ,
      PROD_ID INTEGER NOT NULL,
      PRICE  DOUBLE PRECISION,
      LAST_UPDATED_TIME TIMESTAMP
);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT ORDER_DETAIL_PK Primary Key (ORDER_ID,PROD_ID);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT ORDER_ID_FK Foreign Key (ORDER_ID) REFERENCES ORDERS (ORDER_ID);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT PROD_ID_FK Foreign Key (PROD_ID) REFERENCES PRODUCT (PROD_ID);
CREATE TABLE ORDER_INVOICE (
      INVOICE_ID INTEGER NOT NULL ,
      ORDER_ID INTEGER NOT NULL ,
      DATE_RAISED TIMESTAMP,
      AMOUNT_DUE  DOUBLE PRECISION,
      DATE_SETTLED TIMESTAMP,
      DATE_CANCELLED TIMESTAMP,
      LAST_UPDATED_TIME TIMESTAMP
);
ALTER TABLE ORDER_INVOICE ADD CONSTRAINT ORDER_INVOICE_PK Primary Key (INVOICE_ID);
ALTER TABLE ORDER_INVOICE ADD CONSTRAINT ORDER_INVOICE_FK Foreign Key (ORDER_ID) REFERENCES ORDERS (ORDER_ID);